# Generated by Django 3.1 on 2023-04-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='price',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='unit',
        ),
    ]
