# Generated by Django 3.1 on 2023-04-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_nutrient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='nutrient',
            name='unit',
        ),
    ]
